import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        
        <div><h2>This is my api data </h2></div>

      </main>
    </>
  )
}
export async function getServerSideProps(context) {
  const Postres = await fetch("https://api.energidataservice.dk/dataset/CO2Emis?limit=5");
  const post= await Postres.json();
  console.log(post);
  return {
    props: {}, // will be passed to the page component as props
  }
}
